# Generated by Django 2.2.7 on 2019-11-05 18:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('wordcount', models.IntegerField()),
                ('words', django.contrib.postgres.fields.jsonb.JSONField()),
                ('lines', models.IntegerField()),
            ],
        ),
    ]
